name: Daily 24h Reminders

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Call reminder endpoint
        run: |
          curl -sS -X POST "https://www.ybfstudio.com/api/cron/24h-reminders" \
            -H "Authorization: Bearer $CRON_SECRET"
        env:
          CRON_SECRET: ${{ secrets.CRON_SECRET }}
